### PR TITLE
Update

### PR DESCRIPTION
**Pull request by CasualX**
* Misc minor changes
* Separate obfstr, obfbytes, obfwide
* Improve xref obfuscation
* Improve random for heavy macro use
* Initialize syntax with obfstr

### CODE REVIEW

**Comment by CasualX** [comment]
Closes #41, #42, #43

**Comment by mat-gas** [comment]
Hi, I played a bit with this PR (especially the "improve xref obfuscation"), here's what I found:

- on IDA 7.6 (and Hexrays decompiler), xref are either the "same" as in obfstr 0.3 or are sometimes a bit more obfuscated
- Ghidra succeeds in decoding strings (:scream: )

this is due to hexrays being able to "simplify" equations/code sometimes, but not for every operation. For instance, it doesn't handle well `rol`

here's the toy program used:

image

here's the ASM in IDA 7.6

image

and here's hexrays' output (some constants are changd because I performd multiple tests / compilation, but you get the point)

image


first string is represented as it was in obfstr 0.3 (due to ida "simplifying" shr / xor / ..)

second string has an obfuscated offset because IDA doesn't know (yet) how to simplify `rol` (so it looks like a bit uglier to a reverser)


on Ghidra decompilation output, we can see the strings in clear (it probably perform code emulation and simplifies everything)

- notice the 0x3131313131 / 0x6262626262 (obfstr!("bbbbbb") shown before, and a obfstr!("111111") I had added afterwards)


image



some ideas:
- force adding at lest 1 `rol` to always mess with IDA
- for ghidra, have some kind of global value initialized once at runtime (using "obfuscated" isntructions) and use this in the strings computation to mess with its capabilities?

**Comment by CasualX** [comment]
Thanks for experimenting! Using global mutable state to stop these decompilers from constant folding is interesting but it has some potential downsides:

* Put the values in `.data` instead of `.rdata` (applies to xref and obfuscated string data). This has a big issue that it makes integrity checks impossible, someone could abuse the mutable aspect of these values to change them arbitrarily (for a specific compiled executable). With the data in `.rdata` they can be checked for integrity like normal.

* Dynamically initializing a value at runtime makes `obfstr` not usable in certain contexts (such as code running _before_ that value is initialized) which I would prefer to avoid. Also I'd like to avoid being able to xref this one global variable to find _all_ the places where string obfuscation is taking place.

I've seen some string obfuscation in commercial games that use lazily deobfuscated strings in `.data` that I'm pretty sure are vulnerable to making them turn into arbitrary other strings (as long as space permits) and no ability to guard against it from generic anti-tamper solutions.

Btw you can compile the obfuscation example (`cargo build --example obfuscation --release`) as the playground.

I pushed an update where the offset value is fetched from `.data`, the worst this allows is corruption arbitrary strings at runtime (but the scope is small enough that you can't feasibly make it turn into any other string).

**Comment by mat-gas** [comment]
humm, this seems worse than before, xref are no longer broken/obfuscated:

```
use obfstr::obfstr;
fn main() {
    println!("Hello, world!");
    println!("{}", obfstr!("11111111111111"));
}
```

image

image

**Comment by CasualX** [comment]
I don't understand how that's possible sorry, can you try with the obfuscation.rs example?

My IDA install is currently broken so I'm looking at it with Ghidra and it seems fine:
image

**Comment by mat-gas** [comment]
the `obfuscation` example seems to work:

image


but my test program doesn't:

main.rs
```
use obfstr::obfstr;
fn main() {
    println!("Hello, world!");
    println!("{}", obfstr!("11111111111111"));
}
```
cargo.toml
```
[package]
name = "test_obfstr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obfstr = { git = "https://github.com/CasualX/obfstr.git", branch="update" }
```

image

image



If I fallback on obfstr 0.3, xref are indeed obfuscated:

cargo.toml:

```
[package]
name = "test_obfstr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#obfstr = { git = "https://github.com/CasualX/obfstr.git", branch="update" }
obfstr = "0.3.0"
```


image



no xref on obfuscated data:

image

**Comment by CasualX** [comment]
Random shots in the dark:

* make sure it's actually using the latest version of this branch with `cargo update`
* this may be caused by only having a single obfuscated string in the binary, try having multiple.

I wouldn't really call the `0.3` version of xref obfuscation 'obfuscation'. All it does is prevent trivial 'jump to xref', it should not stop a decompiler from constant folding the simple offset.

**Comment by mat-gas** [comment]
`cargo update` ok

adding a 2nd obfuscated string leads to this one having "broken" xref (but not the first one):

```
use obfstr::obfstr;
fn main() {
    println!("Hello, world!");
    println!("{}", obfstr!("11111111111111"));
    println!("{}", obfstr!("22222222222222"));
}
```


image
 


having 4 of them, the 3 last one have xref broken:

```
use obfstr::obfstr;
fn main() {
    println!("Hello, world!");
    println!("{}", obfstr!("11111111111111"));
    println!("{}", obfstr!("22222222222222"));
    println!("{}", obfstr!("33333333333333"));
    println!("{}", obfstr!("44444444444444"));
}
```

image


downside is, the constant in .data leads to "easy" xref to obfuscated strings:

image



actually, that"s funny, first obfuscated string DOES use a constant in .data (`qword_4F008`) but it's actually "unused" bcause overwritten just after getting it (so hexrays doesn't even show it):

image



whereas it's actually used (in 2nd to 4th string:)

image

**Comment by CasualX** [comment]
I don't understand some of your results, sorry.

> image

It seems the xref obfuscation is correct?

> `v6 = *(_WORD *)((char *)&loc_3425B + v1 + 13) ^ 0xCA1A`

`&loc_3425B` isn't the real location, `&loc_3425B + v1` is, and v1 appears successfully obfuscated.

> but it's actually "unused" bcause overwritten just after getting it (so hexrays doesn't even show it):

This appears to be a legitimate issue that I can reproduce, I'm looking into it.

> downside is, the constant in .data leads to "easy" xref to obfuscated strings:

This may be somewhat mitigated by having the obfuscated strings throughout your source code, they probably won't all be packed together. I'm not sure what else to do to stop decompilers from doing trivial constant folding to stop this.

I'm also considering this out of scope, as the original intent of the library is to prevent automated analysis from discovering _all_ the strings in the program. Being able to deobfuscate the ones scoped to a single function is less of an issue. The idea is to prevent automated scanners from finding these strings, less to prevent dedicated reverse engineers from deobfuscating specific instances.

**Comment by mat-gas** [comment]
in the screenshot, there are 4 obfuscated strings:

- lines 25-28 (obfstr!("11111111111111"));)
- 40-45 (obfstr!("22222222222222"));)
-  56-60 (obfstr!("33333333333333"));)
-  71-75 (obfstr!("44444444444444"));)
- 
the first one has xref no obfuscated (`This appears to be a legitimate issue that I can reproduce, I'm looking into it`.), oters 3 do (:+1:)

IMHO, not having xref to those variables should be nice too: (because no "easy xref to location with obfuscated strings?)
I'm not sure if that was alreayd the case in the first "phase" of the update to 0.4.0 (and I missed it) or if you added it somehow in the following commits

image
  
and yes, defeating constant folding might not be easy

for IDA, using ROL seems to (at least for now) do the trick, so maybe consider "forcing" always using something like this?

for ghidra, except finding "tricks" to defeat its pcode analizer/constant folding algorithm, I don't see any easy solution either

**Comment by CasualX** [comment]
```rust
return ((v >> (seed & 31)) ^ v) & 0xffff;
```

If `seed & 31` is 0 then this whole thing turns to 0 because it simplifies to `v ^ v`.
I considered this case for multiplication and worked around it there but didn't account for this happening with the shifts.

That's what's tripping up here, thanks for catching this edge case in action :)

I replaced the last right shift so there's always a `rol` present.

**Comment by CasualX** [comment]
🥳🎉

**Pull request merged**
